CREATE TABLE `table_chinastocks` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(20) NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `YAHOO_NAME` varchar(20) NOT NULL,
  `IS_ST` int(1) DEFAULT NULL,
  `EXCHANGE` int(4) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3090 DEFAULT CHARSET=utf8;


CREATE TABLE `table_stock_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATE` date NOT NULL,
  `ADJCLOSE` float NOT NULL,
  `CODE` varchar(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=699534 DEFAULT CHARSET=utf8;
